name: Purge JSDelivr CDN

on:
  push:
    branches:
      - main
    paths:
      - 'edlp_data.json'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Staggered Purge Loop (10m)
        run: |
          for i in {1..10}
          do
            echo "Iteration $i/10: Waiting 60s..."
            sleep 60
            echo "Triggering Purge..."
            curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" https://purge.jsdelivr.net/gh/spamfan/optimizer@main/edlp_data.json
          done
